name: Deploy Vite project to GitHub Pages

on:
  push:
    branches:
      - main # Spustí se při každém pushnutí do větve 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Běží na virtuálním stroji s Ubuntu

    steps:
      - name: Checkout code # Krok 1: Stáhne kód repozitáře
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js # Krok 2: Nastaví prostředí Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Můžete zvolit jinou verzi Node.js, pokud potřebujete
          cache: 'npm' # Používá cache pro rychlejší instalaci npm balíčků

      - name: Install dependencies # Krok 3: Nainstaluje závislosti projektu z package.json
        run: npm install # Pokud používáte yarn nebo pnpm, změňte příkaz zde

      - name: Build project # Krok 4: Sestaví váš Vite projekt
        run: npm run build # Spustí skript 'build' definovaný ve vašem package.json

      - name: Upload Pages artifact # Krok 5: Nahraje sestavené soubory pro nasazení
        uses: actions/upload-pages-artifact@v3
        with:
          # Cesta ke složce, kam 'npm run build' ukládá výsledek (obvykle 'dist' pro Vite)
          path: ./dist # Ujistěte se, že toto odpovídá složce generované buildem

  # Krok pro nasazení (standardní pro GitHub Pages)
  deploy:
      environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }} # Získá URL nasazené stránky
      runs-on: ubuntu-latest
      needs: build # Tento job závisí na dokončení jobu 'build'
      steps:
        - name: Deploy to GitHub Pages # Krok 6: Nasadí nahrané soubory na GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4
